### ISSUE TITLE
ValueError  

### ISSUE THREAD

**Issue by emilyhcliu** [kevindougherty-noaa/wdqms#13]
ValueError is found in NCO's parallel processing for `TEMP` at 20240531 12Z cycle.
The error occurred while processing `_genqsat` for station id 47827

```
Traceback (most recent call last):
  File "/lfs/h1/ops/para/packages/gfs.v16.3.16/ush/wdqms.py", line 770, in <module>
    WDQMS(args.input_list, args.type, args.outdir, args.loglevel)
  File "/lfs/h1/ops/para/packages/gfs.v16.3.16/ush/wdqms.py", line 80, in __init__
    tq_df = self._genqsat(tq_df)
  File "/lfs/h1/ops/para/packages/gfs.v16.3.16/ush/wdqms.py", line 517, in _genqsat
    q_df['Obs_Minus_Forecast_adjusted'] = bg_dep
  File "/apps/prod/python-modules/3.8.6/intel/19.1.3.304/lib/python3.8/site-packages/pandas/core/frame.py", line 3163, in __setitem__
    self._set_item(key, value)
  File "/apps/prod/python-modules/3.8.6/intel/19.1.3.304/lib/python3.8/site-packages/pandas/core/frame.py", line 3242, in _set_item
    value = self._sanitize_column(key, value)
  File "/apps/prod/python-modules/3.8.6/intel/19.1.3.304/lib/python3.8/site-packages/pandas/core/frame.py", line 3899, in _sanitize_column
    value = sanitize_index(value, self.index)
  File "/apps/prod/python-modules/3.8.6/intel/19.1.3.304/lib/python3.8/site-packages/pandas/core/internals/construction.py", line 751, in sanitize_index
    raise ValueError(
ValueError: Length of values (91) does not match length of index (90)
398 + rc=1
398 + ((  rc != 0  ))
```
It failed at the following line in wdqms.py due to an inconsistency in  dimension between `bg_def` and `q_df`
```
q_df['Obs_Minus_Forecast_adjusted'] = bg_dep
```

**Comment by emilyhcliu** [comment]
The ValueError is caused by duplicates in the `merged_df`
I have a proposed fix for this:
```
            # Merge dataframes on common keys using an inner join
            merged_df = pd.merge(q_df, t_df, on=['Station_ID', 'Latitude', 'Longitude', 'Pressure', 'Time'], suffixes=('_q', '_t'), how='inner')

            #>>emily
            columns_to_compare = ['Station_ID', 'Latitude', 'Longitude', 'Pressure', 'Time']
            merged_df = merged_df.drop_duplicates(subset=columns_to_compare)
            #<<emily

```

**Comment by emilyhcliu** [comment]
Encountered another `ValueError` for 2024060212 cycle for TEMP
```
 diag_conv_uv_ges.2024060212.nc4 -t TEMP -o /lfs/f1/ops/para/tmp/gdas_atmos_analysis_wdqms_12.150739599.dbqs01
Traceback (most recent call last):
  File "/lfs/h1/ops/para/packages/gfs.v16.3.16/ush/wdqms.py", line 770, in <module>
    WDQMS(args.input_list, args.type, args.outdir, args.loglevel)
  File "/lfs/h1/ops/para/packages/gfs.v16.3.16/ush/wdqms.py", line 80, in __init__
    tq_df = self._genqsat(tq_df)
  File "/lfs/h1/ops/para/packages/gfs.v16.3.16/ush/wdqms.py", line 517, in _genqsat
    q_df['Obs_Minus_Forecast_adjusted'] = bg_dep
  File "/apps/prod/python-modules/3.8.6/intel/19.1.3.304/lib/python3.8/site-packages/pandas/core/frame.py", line 3163, in __setitem__
    self._set_item(key, value)
  File "/apps/prod/python-modules/3.8.6/intel/19.1.3.304/lib/python3.8/site-packages/pandas/core/frame.py", line 3242, in _set_item
    value = self._sanitize_column(key, value)
  File "/apps/prod/python-modules/3.8.6/intel/19.1.3.304/lib/python3.8/site-packages/pandas/core/frame.py", line 3899, in _sanitize_column
    value = sanitize_index(value, self.index)
  File "/apps/prod/python-modules/3.8.6/intel/19.1.3.304/lib/python3.8/site-packages/pandas/core/internals/construction.py", line 751, in sanitize_index
    raise ValueError(
ValueError: Length of values (22) does not match length of index (20)
```

This case, the **Station ID is 48820**

[My fixed](https://github.com/kevindougherty-noaa/wdqms/issues/13#issuecomment-2143284027) did not work for this case.
Under investigating ....
